export default {
    "backgroundColor":"#3e4162",
    "title":{"text":"","subtext":"","sublink":"","left":"center","textStyle":{"color":"#fff"}},
    "tooltip":{"trigger":"item"},
    "legend":{"orient":"vertical","y":"bottom","x":"left","data":[],"textStyle":{"color":"#44c2ed"}},
    "geo":{"map":"china","label":{"emphasis":{"show":false}},
    "regions":[{"name":"南海诸岛","value":0,"itemStyle":{"normal":{"opacity":0,"label":{"show":false}}}}],
    "center":[115.480656,35.23375],
    "roam":true,
    "itemStyle":{"normal":{"areaColor":"#323c48","borderColor":"#111"},
    "emphasis":{"areaColor":"#2a333d"}},"zoom":2},
    "series":[{
      "name":"扫码量",
      "type":"scatter",
      "coordinateSystem":"geo",
      "label":{"normal":{"formatter":"{b}","position":"right","show":false},
      "emphasis":{"show":true}},
      "itemStyle":{"normal":{"color":"#52afff"}},
      "symbolSize":5,
      "data":""
    },{
      "name":"扫码前60-90",
      "type":"effectScatter",
      "coordinateSystem":"geo",
      "showEffectOn":"render",
      "rippleEffect":{"brushType":"stroke"},
      "hoverAnimation":true,
      "label":{"normal":{"formatter":"{b}","position":"right","show":false}},
      "itemStyle":{"normal":{"color":"#27f849","shadowBlur":15,"shadowColor":"#333"}},
      "zlevel":1,
      "symbolSize":6,
      "data":""
    },{
      "name":"扫码前30-60",
      "type":"effectScatter",
      "coordinateSystem":"geo",
      "showEffectOn":"render",
      "rippleEffect":{"brushType":"stroke"},
      "hoverAnimation":true,
      "label":{"normal":{"formatter":"{b}","position":"right","show":false}},
      "itemStyle":{"normal":{"color":"#f6f827","shadowBlur":15,"shadowColor":"#333"}},
      "zlevel":1,
      "symbolSize":7,
      "data":""
    },{
      "name":"扫码前30",
      "type":"effectScatter",
      "coordinateSystem":"geo",
      "showEffectOn":"render",
      "rippleEffect":{"brushType":"stroke"},
      "hoverAnimation":true,
      "label":{"normal":{"formatter":"{b}","position":"right","show":false}},
      "itemStyle":{"normal":{"color":"#f13030","shadowBlur":15,"shadowColor":"#333"}},
      "zlevel":1,
      "symbolSize":8,
      "data":""
    }]
  }